### PR TITLE
MOBILE-2614 Added support for deeplinks

### PR DESCRIPTION
**Pull request by typuk**

### CODE REVIEW

**Review by PocketDaniel — APPROVED** [review]

**Comment by typuk** [comment]
@Holospin Can you please take a look at this PR? This mostly affects Swedish banks that use BankID. We lack Swedish accounts but it should work with Swedish SEB by entering any number and selecting same device.

**Review by Holospin — COMMENTED** [review]
So in Nordea everything worked perfectly for me, but for SEB, I just get infinite loading after entering a number and then selecting "Same device":

https://github.com/getkevin/kevin-ios/assets/56796123/5388d263-06b5-4c82-a57a-7cf3199d58e4

**Comment by typuk** [comment]
@Holospin made an update

**Comment by Holospin** [comment]
> @Holospin made an update

Running into the same issue, getting this errors in the console: 
image

**Review by Holospin — APPROVED** [review]

**Pull request merged**
